// Liste des pays du monde avec leurs traductions
class Countries {
  // Liste des pays en français
  static const List<String> countriesFr = [
    'Afghanistan',
    'Afrique du Sud',
    'Albanie',
    'Algérie',
    'Allemagne',
    'Andorre',
    'Angola',
    'Antigua-et-Barbuda',
    'Arabie Saoudite',
    'Argentine',
    'Arménie',
    'Australie',
    'Autriche',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Belgique',
    'Belize',
    'Bénin',
    'Bhoutan',
    'Biélorussie',
    'Birmanie',
    'Bolivie',
    'Bosnie-Herzégovine',
    'Botswana',
    'Brésil',
    'Brunei',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cambodge',
    'Cameroun',
    'Canada',
    'Cap-Vert',
    'Chili',
    'Chine',
    'Chypre',
    'Colombie',
    'Comores',
    'Congo',
    'Congo (RDC)',
    'Corée du Nord',
    'Corée du Sud',
    'Costa Rica',
    'Côte d\'Ivoire',
    'Croatie',
    'Cuba',
    'Danemark',
    'Djibouti',
    'Dominique',
    'Égypte',
    'Émirats Arabes Unis',
    'Équateur',
    'Érythrée',
    'Espagne',
    'Estonie',
    'Eswatini',
    'États-Unis',
    'Éthiopie',
    'Fidji',
    'Finlande',
    'France',
    'Gabon',
    'Gambie',
    'Géorgie',
    'Ghana',
    'Grèce',
    'Grenade',
    'Guatemala',
    'Guinée',
    'Guinée-Bissau',
    'Guinée Équatoriale',
    'Guyana',
    'Haïti',
    'Honduras',
    'Hongrie',
    'Inde',
    'Indonésie',
    'Irak',
    'Iran',
    'Irlande',
    'Islande',
    'Israël',
    'Italie',
    'Jamaïque',
    'Japon',
    'Jordanie',
    'Kazakhstan',
    'Kenya',
    'Kirghizistan',
    'Kiribati',
    'Koweït',
    'Laos',
    'Lesotho',
    'Lettonie',
    'Liban',
    'Libéria',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macédoine du Nord',
    'Madagascar',
    'Malaisie',
    'Malawi',
    'Maldives',
    'Mali',
    'Malte',
    'Maroc',
    'Marshall',
    'Maurice',
    'Mauritanie',
    'Mexique',
    'Micronésie',
    'Moldavie',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Mozambique',
    'Namibie',
    'Nauru',
    'Népal',
    'Nicaragua',
    'Niger',
    'Nigéria',
    'Norvège',
    'Nouvelle-Zélande',
    'Oman',
    'Ouganda',
    'Ouzbékistan',
    'Pakistan',
    'Palaos',
    'Palestine',
    'Panama',
    'Papouasie-Nouvelle-Guinée',
    'Paraguay',
    'Pays-Bas',
    'Pérou',
    'Philippines',
    'Pologne',
    'Portugal',
    'Qatar',
    'République Centrafricaine',
    'République Dominicaine',
    'République Tchèque',
    'Roumanie',
    'Royaume-Uni',
    'Russie',
    'Rwanda',
    'Saint-Christophe-et-Niévès',
    'Sainte-Lucie',
    'Saint-Marin',
    'Saint-Vincent-et-les-Grenadines',
    'Salomon',
    'Salvador',
    'Samoa',
    'São Tomé-et-Príncipe',
    'Sénégal',
    'Serbie',
    'Seychelles',
    'Sierra Leone',
    'Singapour',
    'Slovaquie',
    'Slovénie',
    'Somalie',
    'Soudan',
    'Soudan du Sud',
    'Sri Lanka',
    'Suède',
    'Suisse',
    'Suriname',
    'Syrie',
    'Tadjikistan',
    'Tanzanie',
    'Tchad',
    'Thaïlande',
    'Timor Oriental',
    'Togo',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turkménistan',
    'Turquie',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Vatican',
    'Venezuela',
    'Viêt Nam',
    'Yémen',
    'Zambie',
    'Zimbabwe',
  ];

  // Liste des pays en anglais
  static const List<String> countriesEn = [
    'Afghanistan',
    'South Africa',
    'Albania',
    'Algeria',
    'Germany',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Saudi Arabia',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Belarus',
    'Myanmar',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Chile',
    'China',
    'Cyprus',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo (DRC)',
    'North Korea',
    'South Korea',
    'Costa Rica',
    'Ivory Coast',
    'Croatia',
    'Cuba',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Egypt',
    'United Arab Emirates',
    'Ecuador',
    'Eritrea',
    'Spain',
    'Estonia',
    'Eswatini',
    'United States',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Equatorial Guinea',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'India',
    'Indonesia',
    'Iraq',
    'Iran',
    'Ireland',
    'Iceland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kyrgyzstan',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesotho',
    'Latvia',
    'Lebanon',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'North Macedonia',
    'Madagascar',
    'Malaysia',
    'Malawi',
    'Maldives',
    'Mali',
    'Malta',
    'Morocco',
    'Marshall Islands',
    'Mauritius',
    'Mauritania',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'New Zealand',
    'Oman',
    'Uganda',
    'Uzbekistan',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Netherlands',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Central African Republic',
    'Dominican Republic',
    'Czech Republic',
    'Romania',
    'United Kingdom',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'San Marino',
    'Saint Vincent and the Grenadines',
    'Solomon Islands',
    'El Salvador',
    'Samoa',
    'São Tomé and Príncipe',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Sudan',
    'South Sudan',
    'Sri Lanka',
    'Sweden',
    'Switzerland',
    'Suriname',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Chad',
    'Thailand',
    'East Timor',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkmenistan',
    'Turkey',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];

  // Liste des pays en espagnol
  static const List<String> countriesEs = [
    'Afganistán',
    'Sudáfrica',
    'Albania',
    'Argelia',
    'Alemania',
    'Andorra',
    'Angola',
    'Antigua y Barbuda',
    'Arabia Saudita',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaiyán',
    'Bahamas',
    'Baréin',
    'Bangladés',
    'Barbados',
    'Bélgica',
    'Belice',
    'Benín',
    'Bután',
    'Bielorrusia',
    'Birmania',
    'Bolivia',
    'Bosnia y Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunéi',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Camboya',
    'Camerún',
    'Canadá',
    'Cabo Verde',
    'Chile',
    'China',
    'Chipre',
    'Colombia',
    'Comoras',
    'Congo',
    'Congo (RDC)',
    'Corea del Norte',
    'Corea del Sur',
    'Costa Rica',
    'Costa de Marfil',
    'Croacia',
    'Cuba',
    'Dinamarca',
    'Yibuti',
    'Dominica',
    'Egipto',
    'Emiratos Árabes Unidos',
    'Ecuador',
    'Eritrea',
    'España',
    'Estonia',
    'Esuatini',
    'Estados Unidos',
    'Etiopía',
    'Fiyi',
    'Finlandia',
    'Francia',
    'Gabón',
    'Gambia',
    'Georgia',
    'Ghana',
    'Grecia',
    'Granada',
    'Guatemala',
    'Guinea',
    'Guinea-Bisáu',
    'Guinea Ecuatorial',
    'Guyana',
    'Haití',
    'Honduras',
    'Hungría',
    'India',
    'Indonesia',
    'Irak',
    'Irán',
    'Irlanda',
    'Islandia',
    'Israel',
    'Italia',
    'Jamaica',
    'Japón',
    'Jordania',
    'Kazajistán',
    'Kenia',
    'Kirguistán',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letonia',
    'Líbano',
    'Liberia',
    'Libia',
    'Liechtenstein',
    'Lituania',
    'Luxemburgo',
    'Macedonia del Norte',
    'Madagascar',
    'Malasia',
    'Malaui',
    'Maldivas',
    'Malí',
    'Malta',
    'Marruecos',
    'Islas Marshall',
    'Mauricio',
    'Mauritania',
    'México',
    'Micronesia',
    'Moldavia',
    'Mónaco',
    'Mongolia',
    'Montenegro',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Níger',
    'Nigeria',
    'Noruega',
    'Nueva Zelanda',
    'Omán',
    'Uganda',
    'Uzbekistán',
    'Pakistán',
    'Palaos',
    'Palestina',
    'Panamá',
    'Papúa Nueva Guinea',
    'Paraguay',
    'Países Bajos',
    'Perú',
    'Filipinas',
    'Polonia',
    'Portugal',
    'Catar',
    'República Centroafricana',
    'República Dominicana',
    'República Checa',
    'Rumania',
    'Reino Unido',
    'Rusia',
    'Ruanda',
    'San Cristóbal y Nieves',
    'Santa Lucía',
    'San Marino',
    'San Vicente y las Granadinas',
    'Islas Salomón',
    'El Salvador',
    'Samoa',
    'Santo Tomé y Príncipe',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leona',
    'Singapur',
    'Eslovaquia',
    'Eslovenia',
    'Somalia',
    'Sudán',
    'Sudán del Sur',
    'Sri Lanka',
    'Suecia',
    'Suiza',
    'Surinam',
    'Siria',
    'Tayikistán',
    'Tanzania',
    'Chad',
    'Tailandia',
    'Timor Oriental',
    'Togo',
    'Tonga',
    'Trinidad y Tobago',
    'Túnez',
    'Turkmenistán',
    'Turquía',
    'Tuvalu',
    'Ucrania',
    'Uruguay',
    'Vanuatu',
    'Ciudad del Vaticano',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabue',
  ];

  // Méthode pour obtenir la liste selon la langue
  static List<String> getCountries(String languageCode) {
    switch (languageCode) {
      case 'fr':
        return countriesFr;
      case 'es':
        return countriesEs;
      case 'en':
      default:
        return countriesEn;
    }
  }
}
